using System.ComponentModel;
using Grimoire.Wiki;
using ModelContextProtocol.Server;

namespace Grimoire.Hub.Mcp;

/// <summary>Who a page written through the tools was generated by (WIKI-002).</summary>
/// <remarks>
/// Which run a tool call belongs to is the route's — <c>/mcp/{door}/{runId}</c> — and is read by
/// <see cref="WikiToolSurfaces"/>; nothing a tool writes carries it.
/// </remarks>
public sealed class PageProducer(string model)
{
    /// <summary>
    /// Who generated a page: Grimoire, and the model the run was served by. This is the whole of
    /// what Grimoire writes into the wiki (WIKI-002, Constitution V.1).
    /// </summary>
    /// <remarks>
    /// The <c>&lt;producer&gt;/&lt;version&gt;</c> form of OKF 0.2 §7, which admits three spellings
    /// of an actor and no free text; the standard's own example is
    /// <c>reference_agent/gemini-2.5-pro</c>. The root index declares <c>okf_version: "0.2"</c>, so
    /// a record in any other shape is a claim the wiki does not honour.
    /// <para>
    /// The run identifier is deliberately not here. An actor is one actor, and the page was
    /// produced by the agent rather than by a run; what the run did is in the log entry, which
    /// names every file it touched, and <see cref="GenerationRecord.At"/> dates the page.
    /// </para>
    /// </remarks>
    public string GeneratedBy => $"grimoire/{model}";
}

/// <summary>
/// The five tools an ingest run may use, served over MCP at the run's own endpoint. This list is the
/// grant, and the grant is the agent's entire tool surface (GUARD-001, GUARD-002).
/// </summary>
/// <remarks>
/// <c>write_page</c> stamps; <c>write_index</c> and <c>append_log</c> do not, because indexes and
/// the log are not pages (data-model.md). Nothing here removes, moves, reverts or commits: the
/// port has no such call, and a first ingest needs none.
/// </remarks>
[McpServerToolType]
public sealed class WikiToolsServer(IWikiStore wiki, PageProducer producer, TimeProvider clock)
{
    /// <summary>The bare names this server serves, in the order the grant records them.</summary>
    public static IReadOnlyList<string> ServedNames => WikiReadToolsServer.NamesOf(typeof(WikiToolsServer));

    [McpServerTool(Name = "list_pages")]
    [Description("Every path in the wiki, relative to its root.")]
    public Task<object> ListPagesAsync(CancellationToken cancellationToken) =>
        WikiReads.ListPagesAsync(wiki, cancellationToken);

    [McpServerTool(Name = "read_page")]
    [Description("One file's full text, frontmatter included.")]
    public Task<object> ReadPageAsync(
        [Description("Path relative to the wiki root.")] string path,
        CancellationToken cancellationToken) =>
        WikiReads.ReadPageAsync(wiki, path, cancellationToken);

    [McpServerTool(Name = "write_page")]
    [Description("Create a page or replace it whole. Grimoire records who generated it and when.")]
    public async Task<object> WritePageAsync(
        [Description("Path relative to the wiki root.")] string path,
        [Description("The page's full text, frontmatter included.")] string content,
        CancellationToken cancellationToken)
    {
        if (WikiFile.IsReservedForSomethingOtherThanAPage(path))
        {
            // An index carries no generation record and the log is not a page, so both have tools
            // of their own. Written through this one they would be stamped as pages
            // (WIKI-002, data-model.md).
            return Refused(
                "not-a-page",
                $"\"{path}\" is an index or the log; use write_index or append_log");
        }

        var record = new GenerationRecord(producer.GeneratedBy, clock.GetUtcNow());
        var stamped = ProvenanceStamp.Apply(content, record);

        if (stamped.Page is null)
        {
            // The place for the record cannot be read: the write fails and the agent is told why
            // (WIKI-002). Nothing else about the page is judged.
            return Refused("frontmatter-unreadable", stamped.Error!);
        }

        try
        {
            await wiki.WriteAsync(path, stamped.Page, cancellationToken).ConfigureAwait(false);
            return new { written = path, generated = new { by = record.By, at = record.At } };
        }
        catch (OutsideWikiException outside)
        {
            return Refused("outside-wiki", outside.Message);
        }
    }

    [McpServerTool(Name = "write_index")]
    [Description("Create or replace a section index or the root index. Carries no generation record.")]
    public async Task<object> WriteIndexAsync(
        [Description("Path relative to the wiki root.")] string path,
        [Description("The index's full text.")] string content,
        CancellationToken cancellationToken)
    {
        if (!WikiFile.IsAnIndex(path))
        {
            // This tool writes without a generation record. Pointed at a page it would create one
            // that no run is recorded as having generated, which is the whole of WIKI-002.
            return Refused("not-an-index", $"\"{path}\" is not an {WikiFile.Index}");
        }

        try
        {
            await wiki.WriteAsync(path, content, cancellationToken).ConfigureAwait(false);
            return new { written = path };
        }
        catch (OutsideWikiException outside)
        {
            return Refused("outside-wiki", outside.Message);
        }
    }

    [McpServerTool(Name = "append_log")]
    [Description("Add an entry to the wiki's log. Carries no generation record.")]
    public async Task<object> AppendLogAsync(
        [Description("The entry, which must identify this run.")] string entry,
        CancellationToken cancellationToken)
    {
        await wiki.AppendLogAsync(entry, cancellationToken).ConfigureAwait(false);
        return new { appended = WikiFile.Log };
    }

    private static object Refused(string reason, string message) => WikiReads.Refused(reason, message);
}
