<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Grimoire.Tests.Architecture</RootNamespace>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/hub/Grimoire.Hub.csproj" />
    <ProjectReference Include="../../src/egress/Grimoire.Egress.csproj" />
  </ItemGroup>

</Project>
